# Generated by Django 5.1.3 on 2024-12-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
