# Generated by Django 5.1.3 on 2024-11-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_dietaryrestrictions_menuitemdietaryrestrictions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietaryrestrictions',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='menuitemdietaryrestrictions',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='menuitemdietaryrestrictions',
            old_name='restriction_id',
            new_name='restriction',
        ),
        migrations.RenameField(
            model_name='menuitems',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='menuprocessinglogs',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='menus',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='menusections',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='menuitemdietaryrestrictions',
            unique_together={('item', 'restriction')},
        ),
    ]
