# Generated by Django 5.1.3 on 2024-12-01 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_rename_restaurant_dietaryrestrictions_restaurant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuprocessinglogs',
            name='version_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='menu_app.menu_versions'),
        ),
    ]
